import { getTranslations } from 'next-intl/server';
import { api, getWorkspaceId } from '@/lib/api';
import { createLlmConnection, removeLlmConnection, verifyLlmConnection } from '../actions';

type Connection={id:string;provider:string;name:string;accountLabel?:string;status:string;ownerConcurrencyLimit:number;healthScore:number;ownerUserId:string;models:{model:string}[]};

export default async function LlmPage({params}:{params:Promise<{locale:string}>}){
  const {locale}=await params;
  const t=await getTranslations('llm');
  const workspaceId=await getWorkspaceId();
  const connections=await api<Connection[]>(`/workspaces/${workspaceId}/llm/connections`);
  return <div className="space-y-7"><div><h1 className="text-3xl font-semibold">{t('title')}</h1><p className="mt-3 max-w-3xl text-slate-400">{t('subtitle')}</p></div><form action={createLlmConnection} className="panel grid gap-3 p-5 md:grid-cols-3"><input type="hidden" name="locale" value={locale}/><input name="name" required placeholder="Connection name" className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2"/><input name="accountLabel" placeholder="abc@example.com" className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2"/><select name="provider" className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2">{['OPENAI','OPENROUTER','ANTHROPIC','GEMINI','GITHUB_MODELS','CUSTOM_OPENAI_COMPATIBLE'].map((provider)=><option key={provider}>{provider}</option>)}</select><input name="model" required placeholder="Model ID" className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2"/><input name="baseUrl" placeholder="Custom base URL" className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2"/><input name="credential" type="password" required placeholder="API credential" className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2"/><input name="ownerConcurrencyLimit" type="number" min="1" max="50" defaultValue="2" className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2"/><button className="rounded-lg bg-violet-600 px-4 py-2 font-medium md:col-span-2">Add account to shared pool</button></form><div className="space-y-3">{connections.map((connection)=><article key={connection.id} className="panel flex flex-wrap items-center justify-between gap-4 p-5"><div><strong>{connection.provider} · {connection.name}</strong><p className="text-sm text-slate-400">{connection.models.map((model)=>model.model).join(', ')}</p><p className="text-xs text-slate-500">Health {connection.healthScore}/100 · Capacity {connection.ownerConcurrencyLimit} · {connection.status}</p></div><div className="flex gap-2"><form action={verifyLlmConnection}><input type="hidden" name="id" value={connection.id}/><input type="hidden" name="locale" value={locale}/><button className="rounded bg-slate-700 px-3 py-2 text-sm">Verify</button></form><form action={removeLlmConnection}><input type="hidden" name="id" value={connection.id}/><input type="hidden" name="locale" value={locale}/><button className="rounded bg-red-950 px-3 py-2 text-sm text-red-300">Remove</button></form></div></article>)}{connections.length===0&&<div className="panel p-8 text-slate-400">Add the first provider account above.</div>}</div></div>;
}
