import { getTranslations } from 'next-intl/server';
import { ExternalLink } from 'lucide-react';
import { api, workspaceId } from '@/lib/api';
import { updateLeadStatus } from '../actions';

type Lead = { id: string; status: string; priorityScore: number; priorityLevel: string; post: { title: string; subreddit: string; permalink: string }; classification: { signalType: string; summary: string; provider: string; model: string } };
export default async function LeadsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const t = await getTranslations('leads');
  const leads = await api<Lead[]>(`/workspaces/${workspaceId}/leads`);
  return <div><h1 className="text-3xl font-semibold">{t('title')}</h1><div className="panel mt-7 overflow-hidden">{leads.length === 0 ? <p className="p-8 text-slate-400">{t('empty')}</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-700 text-slate-400"><tr><th className="p-4">{t('priority')}</th><th className="p-4">Lead</th><th className="p-4">{t('signal')}</th><th className="p-4">Model</th><th className="p-4">{t('status')}</th></tr></thead><tbody>{leads.map((lead) => <tr key={lead.id} className="border-b border-slate-800/80 align-top"><td className="p-4"><span className="rounded-full bg-violet-500/15 px-3 py-1 text-violet-300">{lead.priorityLevel} · {lead.priorityScore}</span></td><td className="max-w-xl p-4"><a href={lead.post.permalink} target="_blank" className="font-medium hover:text-violet-300">{lead.post.title} <ExternalLink className="inline" size={14}/></a><p className="mt-2 text-slate-400">{lead.classification.summary}</p><span className="mt-2 inline-block text-xs text-slate-500">r/{lead.post.subreddit}</span></td><td className="p-4">{lead.classification.signalType}</td><td className="p-4 text-slate-400">{lead.classification.provider}<br/>{lead.classification.model}</td><td className="p-4"><form action={updateLeadStatus}><input type="hidden" name="id" value={lead.id}/><input type="hidden" name="locale" value={locale}/><select name="status" defaultValue={lead.status} className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2">{['NEW','REVIEWING','QUALIFIED','ASSIGNED','CONTACTED','CONVERTED','REJECTED','ARCHIVED'].map((s) => <option key={s}>{s}</option>)}</select><button className="ml-2 rounded-lg bg-violet-600 px-3 py-2 text-xs">Save</button></form></td></tr>)}</tbody></table></div>}</div></div>;
}
